Team.delete_all
Team.create!({"id"=>2, "name"=>"Bourne/Moore"})
Team.create!({"id"=>1, "name"=>"Scott/Sroufe "})
Team.create!({"id"=>3, "name"=>"Coker/Coker"})
Team.create!({"id"=>4, "name"=>"Askew/Barrett"})
Team.create!({"id"=>5, "name"=>"Gillanders/Oliver"})
Team.create!({"id"=>6, "name"=>"Axten-Rice/Nippert"})
Player.delete_all
Player.create!({"id"=>14, "first_name"=>"Calvert", "last_name"=>"Scott", "username"=>"oldskin", "strengths"=>nil, "weaknesses"=>nil, "handicap_text"=>nil, "handicap"=>nil, "team_id"=>1, "best_moment"=>nil, "nick_name"=>nil, "home_club"=>nil, "trophies"=>nil})
Player.create!({"id"=>15, "first_name"=>"Sam", "last_name"=>"Bourne", "username"=>"bournie", "strengths"=>nil, "weaknesses"=>nil, "handicap_text"=>nil, "handicap"=>nil, "team_id"=>2, "best_moment"=>nil, "nick_name"=>nil, "home_club"=>nil, "trophies"=>nil})
Player.create!({"id"=>16, "first_name"=>"Hayden", "last_name"=>"Moore", "username"=>"moo", "strengths"=>nil, "weaknesses"=>nil, "handicap_text"=>nil, "handicap"=>nil, "team_id"=>2, "best_moment"=>nil, "nick_name"=>nil, "home_club"=>nil, "trophies"=>nil})
Player.create!({"id"=>17, "first_name"=>"Matt", "last_name"=>"Sroufe ", "username"=>"money", "strengths"=>"", "weaknesses"=>"", "handicap_text"=>"", "handicap"=>nil, "team_id"=>1, "best_moment"=>nil, "nick_name"=>nil, "home_club"=>nil, "trophies"=>nil})
Player.create!({"id"=>18, "first_name"=>"Michael", "last_name"=>"Coker", "username"=>"cokes", "strengths"=>nil, "weaknesses"=>nil, "handicap_text"=>nil, "handicap"=>nil, "team_id"=>3, "best_moment"=>nil, "nick_name"=>nil, "home_club"=>nil, "trophies"=>nil})
Player.create!({"id"=>19, "first_name"=>"Toby", "last_name"=>"Gillanders", "username"=>"tobz", "strengths"=>nil, "weaknesses"=>nil, "handicap_text"=>nil, "handicap"=>nil, "team_id"=>5, "best_moment"=>nil, "nick_name"=>nil, "home_club"=>nil, "trophies"=>nil})
Player.create!({"id"=>20, "first_name"=>"Ben", "last_name"=>"Oliver", "username"=>"ben", "strengths"=>nil, "weaknesses"=>nil, "handicap_text"=>nil, "handicap"=>nil, "team_id"=>5, "best_moment"=>nil, "nick_name"=>nil, "home_club"=>nil, "trophies"=>nil})
Player.create!({"id"=>21, "first_name"=>"Sam", "last_name"=>"Askew", "username"=>"asqboi69", "strengths"=>nil, "weaknesses"=>nil, "handicap_text"=>nil, "handicap"=>nil, "team_id"=>4, "best_moment"=>nil, "nick_name"=>nil, "home_club"=>nil, "trophies"=>nil})
Player.create!({"id"=>22, "first_name"=>"Lee", "last_name"=>"Axten-Rice", "username"=>"lee", "strengths"=>nil, "weaknesses"=>nil, "handicap_text"=>nil, "handicap"=>nil, "team_id"=>6, "best_moment"=>nil, "nick_name"=>nil, "home_club"=>nil, "trophies"=>nil})
Player.create!({"id"=>23, "first_name"=>"Jonny", "last_name"=>"Nippert", "username"=>"jfunk", "strengths"=>"", "weaknesses"=>"", "handicap_text"=>"", "handicap"=>nil, "team_id"=>6, "best_moment"=>nil, "nick_name"=>nil, "home_club"=>nil, "trophies"=>nil})
Player.create!({"id"=>24, "first_name"=>"Adam", "last_name"=>"Barrett", "username"=>"ayebee", "strengths"=>"", "weaknesses"=>"", "handicap_text"=>"", "handicap"=>nil, "team_id"=>4, "best_moment"=>nil, "nick_name"=>nil, "home_club"=>nil, "trophies"=>nil})
Player.create!({"id"=>25, "first_name"=>"Matthew", "last_name"=>"Coker", "username"=>"chubbs", "strengths"=>"This man is an absolute fan favorite, often refered to as the rockstar of the C F cup group. His strengths start straight away with his shaft handling skills, this leads into a lovely controlled low cut drive. Around the greens his hinge and hold touch is something to behold. Chubbs is certainly one to watch out for on this seasons tour", "weaknesses"=>"The longer the irons get the more his game unravels, catch\r\nChubbs with the right Heckle from 170 or so out and he starts wobbling in his boots. Chubbs likes to think of himself as a bit of a trickster which dosnt always pay off. his most famous \"trickshot\" was hitting a tee shot between his legs and sticking his opponents foot with the ball", "handicap_text"=>"", "handicap"=>"14.8", "team_id"=>3, "best_moment"=>"Vomiting in the lovely lush garden surrounding the tee box on martinbourgh hole 9! an outstanding effort to keep the spew down for so long", "nick_name"=>"Chubbs", "home_club"=>"Hastings", "trophies"=>"Current holder of \"The Pigs\""})
Course.delete_all
Course.create!({"id"=>1, "name"=>"Terrace Downs"})
Course.create!({"id"=>2, "name"=>"Pegasus"})
Course.create!({"id"=>3, "name"=>"Clearwater"})
Hole.delete_all
Hole.create!({"id"=>1, "course_id"=>1, "par"=>5, "stroke"=>15, "meters"=>nil, "number"=>1})
Hole.create!({"id"=>2, "course_id"=>1, "par"=>4, "stroke"=>11, "meters"=>nil, "number"=>2})
Hole.create!({"id"=>3, "course_id"=>1, "par"=>4, "stroke"=>13, "meters"=>nil, "number"=>3})
Hole.create!({"id"=>4, "course_id"=>1, "par"=>3, "stroke"=>9, "meters"=>nil, "number"=>4})
Hole.create!({"id"=>5, "course_id"=>1, "par"=>4, "stroke"=>5, "meters"=>nil, "number"=>5})
Hole.create!({"id"=>6, "course_id"=>1, "par"=>3, "stroke"=>17, "meters"=>nil, "number"=>6})
Hole.create!({"id"=>7, "course_id"=>1, "par"=>5, "stroke"=>7, "meters"=>nil, "number"=>7})
Hole.create!({"id"=>8, "course_id"=>1, "par"=>4, "stroke"=>3, "meters"=>nil, "number"=>8})
Hole.create!({"id"=>9, "course_id"=>1, "par"=>4, "stroke"=>1, "meters"=>nil, "number"=>9})
Hole.create!({"id"=>10, "course_id"=>1, "par"=>3, "stroke"=>8, "meters"=>nil, "number"=>10})
Hole.create!({"id"=>11, "course_id"=>1, "par"=>4, "stroke"=>2, "meters"=>nil, "number"=>11})
Hole.create!({"id"=>12, "course_id"=>1, "par"=>5, "stroke"=>10, "meters"=>nil, "number"=>12})
Hole.create!({"id"=>13, "course_id"=>1, "par"=>4, "stroke"=>6, "meters"=>nil, "number"=>13})
Hole.create!({"id"=>14, "course_id"=>1, "par"=>4, "stroke"=>12, "meters"=>nil, "number"=>14})
Hole.create!({"id"=>15, "course_id"=>1, "par"=>4, "stroke"=>14, "meters"=>nil, "number"=>15})
Hole.create!({"id"=>16, "course_id"=>1, "par"=>3, "stroke"=>18, "meters"=>nil, "number"=>16})
Hole.create!({"id"=>17, "course_id"=>1, "par"=>4, "stroke"=>4, "meters"=>nil, "number"=>17})
Hole.create!({"id"=>18, "course_id"=>1, "par"=>5, "stroke"=>16, "meters"=>nil, "number"=>18})
Match.delete_all
Match.create!({"id"=>1, "course_id"=>1, "date"=>"2022-04-29"})
Match.create!({"id"=>6, "course_id"=>1, "date"=>"2022-04-29"})
Match.create!({"id"=>7, "course_id"=>1, "date"=>"2022-04-29"})
MatchTeam.delete_all
MatchTeam.create!({"id"=>1, "match_id"=>1, "team_id"=>1})
MatchTeam.create!({"id"=>2, "match_id"=>1, "team_id"=>2})
MatchTeam.create!({"id"=>9, "match_id"=>6, "team_id"=>3})
MatchTeam.create!({"id"=>10, "match_id"=>6, "team_id"=>5})
MatchTeam.create!({"id"=>11, "match_id"=>7, "team_id"=>6})
MatchTeam.create!({"id"=>12, "match_id"=>7, "team_id"=>4})
Score.delete_all
