Team.delete_all
Team.create!({"id"=>1, "name"=>"Caddyshack"})
Team.create!({"id"=>2, "name"=>"Caddyshack"})
Player.delete_all
Player.create!({"id"=>14, "first_name"=>"Calvert", "last_name"=>"Scott", "username"=>"oldskin", "strengths"=>nil, "weaknesses"=>nil, "handicap_text"=>nil, "handicap"=>nil, "team_id"=>1})
Player.create!({"id"=>15, "first_name"=>"Sam", "last_name"=>"Bourne", "username"=>"bournie", "strengths"=>nil, "weaknesses"=>nil, "handicap_text"=>nil, "handicap"=>nil, "team_id"=>2})
Player.create!({"id"=>16, "first_name"=>"Hayden", "last_name"=>"Moore", "username"=>"moo", "strengths"=>nil, "weaknesses"=>nil, "handicap_text"=>nil, "handicap"=>nil, "team_id"=>2})
Player.create!({"id"=>17, "first_name"=>"Matt", "last_name"=>"Sroufe ", "username"=>"money", "strengths"=>"", "weaknesses"=>"", "handicap_text"=>"", "handicap"=>nil, "team_id"=>1})
Course.delete_all
Course.create!({"id"=>1, "name"=>"Terrace Downs"})
Course.create!({"id"=>2, "name"=>"Pegasus"})
Course.create!({"id"=>3, "name"=>"Clearwater"})
Hole.delete_all
Hole.create!({"id"=>1, "course_id"=>1, "par"=>5, "stroke"=>15, "meters"=>nil, "number"=>1})
Hole.create!({"id"=>2, "course_id"=>1, "par"=>4, "stroke"=>11, "meters"=>nil, "number"=>2})
Hole.create!({"id"=>3, "course_id"=>1, "par"=>4, "stroke"=>13, "meters"=>nil, "number"=>3})
Hole.create!({"id"=>4, "course_id"=>1, "par"=>3, "stroke"=>9, "meters"=>nil, "number"=>4})
Hole.create!({"id"=>5, "course_id"=>1, "par"=>4, "stroke"=>5, "meters"=>nil, "number"=>5})
Hole.create!({"id"=>6, "course_id"=>1, "par"=>3, "stroke"=>17, "meters"=>nil, "number"=>6})
Hole.create!({"id"=>7, "course_id"=>1, "par"=>5, "stroke"=>7, "meters"=>nil, "number"=>7})
Hole.create!({"id"=>8, "course_id"=>1, "par"=>4, "stroke"=>3, "meters"=>nil, "number"=>8})
Hole.create!({"id"=>9, "course_id"=>1, "par"=>4, "stroke"=>1, "meters"=>nil, "number"=>9})
Hole.create!({"id"=>10, "course_id"=>1, "par"=>3, "stroke"=>8, "meters"=>nil, "number"=>10})
Hole.create!({"id"=>11, "course_id"=>1, "par"=>4, "stroke"=>2, "meters"=>nil, "number"=>11})
Hole.create!({"id"=>12, "course_id"=>1, "par"=>5, "stroke"=>10, "meters"=>nil, "number"=>12})
Hole.create!({"id"=>13, "course_id"=>1, "par"=>4, "stroke"=>6, "meters"=>nil, "number"=>13})
Hole.create!({"id"=>14, "course_id"=>1, "par"=>4, "stroke"=>12, "meters"=>nil, "number"=>14})
Hole.create!({"id"=>15, "course_id"=>1, "par"=>4, "stroke"=>14, "meters"=>nil, "number"=>15})
Hole.create!({"id"=>16, "course_id"=>1, "par"=>3, "stroke"=>18, "meters"=>nil, "number"=>16})
Hole.create!({"id"=>17, "course_id"=>1, "par"=>4, "stroke"=>4, "meters"=>nil, "number"=>17})
Hole.create!({"id"=>18, "course_id"=>1, "par"=>5, "stroke"=>16, "meters"=>nil, "number"=>18})
Match.delete_all
Match.create!({"id"=>1, "course_id"=>1, "date"=>"2022-04-29"})
MatchTeam.delete_all
MatchTeam.create!({"id"=>1, "match_id"=>1, "team_id"=>1})
MatchTeam.create!({"id"=>2, "match_id"=>1, "team_id"=>2})
Score.delete_all
Score.create!({"id"=>1, "match_id"=>1, "hole_id"=>1, "player_id"=>13, "score"=>4})
Score.create!({"id"=>3, "match_id"=>1, "hole_id"=>1, "player_id"=>5, "score"=>4})
Score.create!({"id"=>4, "match_id"=>1, "hole_id"=>1, "player_id"=>3, "score"=>5})
Score.create!({"id"=>6, "match_id"=>1, "hole_id"=>2, "player_id"=>3, "score"=>4})
Score.create!({"id"=>7, "match_id"=>1, "hole_id"=>2, "player_id"=>3, "score"=>4})
Score.create!({"id"=>9, "match_id"=>1, "hole_id"=>2, "player_id"=>13, "score"=>6})
Score.create!({"id"=>15, "match_id"=>1, "hole_id"=>12, "player_id"=>3, "score"=>8})
Score.create!({"id"=>16, "match_id"=>1, "hole_id"=>5, "player_id"=>7, "score"=>5})
Score.create!({"id"=>8, "match_id"=>1, "hole_id"=>2, "player_id"=>5, "score"=>5})
Score.create!({"id"=>2, "match_id"=>1, "hole_id"=>1, "player_id"=>7, "score"=>5})
Score.create!({"id"=>12, "match_id"=>1, "hole_id"=>3, "player_id"=>5, "score"=>4})
Score.create!({"id"=>13, "match_id"=>1, "hole_id"=>3, "player_id"=>3, "score"=>8})
Score.create!({"id"=>20, "match_id"=>1, "hole_id"=>5, "player_id"=>13, "score"=>4})
Score.create!({"id"=>21, "match_id"=>1, "hole_id"=>5, "player_id"=>5, "score"=>5})
Score.create!({"id"=>22, "match_id"=>1, "hole_id"=>5, "player_id"=>3, "score"=>3})
Score.create!({"id"=>24, "match_id"=>1, "hole_id"=>6, "player_id"=>7, "score"=>4})
Score.create!({"id"=>26, "match_id"=>1, "hole_id"=>6, "player_id"=>5, "score"=>5})
Score.create!({"id"=>27, "match_id"=>1, "hole_id"=>6, "player_id"=>3, "score"=>4})
Score.create!({"id"=>23, "match_id"=>1, "hole_id"=>7, "player_id"=>13, "score"=>5})
Score.create!({"id"=>29, "match_id"=>1, "hole_id"=>7, "player_id"=>5, "score"=>8})
Score.create!({"id"=>30, "match_id"=>1, "hole_id"=>7, "player_id"=>3, "score"=>4})
Score.create!({"id"=>31, "match_id"=>1, "hole_id"=>9, "player_id"=>7, "score"=>2})
Score.create!({"id"=>32, "match_id"=>1, "hole_id"=>9, "player_id"=>13, "score"=>5})
Score.create!({"id"=>33, "match_id"=>1, "hole_id"=>9, "player_id"=>5, "score"=>3})
Score.create!({"id"=>34, "match_id"=>1, "hole_id"=>9, "player_id"=>3, "score"=>7})
Score.create!({"id"=>38, "match_id"=>1, "hole_id"=>8, "player_id"=>3, "score"=>5})
Score.create!({"id"=>36, "match_id"=>1, "hole_id"=>8, "player_id"=>13, "score"=>3})
Score.create!({"id"=>37, "match_id"=>1, "hole_id"=>8, "player_id"=>5, "score"=>3})
Score.create!({"id"=>35, "match_id"=>1, "hole_id"=>8, "player_id"=>7, "score"=>5})
Score.create!({"id"=>39, "match_id"=>1, "hole_id"=>10, "player_id"=>7, "score"=>5})
Score.create!({"id"=>40, "match_id"=>1, "hole_id"=>10, "player_id"=>13, "score"=>2})
Score.create!({"id"=>41, "match_id"=>1, "hole_id"=>10, "player_id"=>5, "score"=>5})
Score.create!({"id"=>42, "match_id"=>1, "hole_id"=>10, "player_id"=>3, "score"=>3})
Score.create!({"id"=>43, "match_id"=>1, "hole_id"=>11, "player_id"=>7, "score"=>3})
Score.create!({"id"=>44, "match_id"=>1, "hole_id"=>11, "player_id"=>13, "score"=>2})
Score.create!({"id"=>45, "match_id"=>1, "hole_id"=>11, "player_id"=>5, "score"=>4})
Score.create!({"id"=>46, "match_id"=>1, "hole_id"=>11, "player_id"=>3, "score"=>3})
Score.create!({"id"=>5, "match_id"=>1, "hole_id"=>2, "player_id"=>7, "score"=>3})
Score.create!({"id"=>47, "match_id"=>1, "hole_id"=>12, "player_id"=>5, "score"=>4})
Score.create!({"id"=>10, "match_id"=>1, "hole_id"=>3, "player_id"=>7, "score"=>5})
Score.create!({"id"=>14, "match_id"=>1, "hole_id"=>3, "player_id"=>13, "score"=>3})
Score.create!({"id"=>49, "match_id"=>1, "hole_id"=>13, "player_id"=>5, "score"=>8})
Score.create!({"id"=>50, "match_id"=>1, "hole_id"=>13, "player_id"=>3, "score"=>4})
Score.create!({"id"=>51, "match_id"=>1, "hole_id"=>12, "player_id"=>13, "score"=>2})
Score.create!({"id"=>48, "match_id"=>1, "hole_id"=>13, "player_id"=>13, "score"=>3})
Score.create!({"id"=>52, "match_id"=>1, "hole_id"=>13, "player_id"=>7, "score"=>3})
Score.create!({"id"=>11, "match_id"=>1, "hole_id"=>4, "player_id"=>7, "score"=>6})
Score.create!({"id"=>18, "match_id"=>1, "hole_id"=>4, "player_id"=>5, "score"=>5})
Score.create!({"id"=>19, "match_id"=>1, "hole_id"=>4, "player_id"=>3, "score"=>3})
Score.create!({"id"=>17, "match_id"=>1, "hole_id"=>4, "player_id"=>13, "score"=>5})
Score.create!({"id"=>28, "match_id"=>1, "hole_id"=>7, "player_id"=>7, "score"=>3})
Score.create!({"id"=>25, "match_id"=>1, "hole_id"=>6, "player_id"=>13, "score"=>6})
Score.create!({"id"=>53, "match_id"=>1, "hole_id"=>12, "player_id"=>7, "score"=>4})
Score.create!({"id"=>55, "match_id"=>1, "hole_id"=>14, "player_id"=>13, "score"=>3})
Score.create!({"id"=>56, "match_id"=>1, "hole_id"=>14, "player_id"=>5, "score"=>7})
Score.create!({"id"=>57, "match_id"=>1, "hole_id"=>14, "player_id"=>3, "score"=>5})
Score.create!({"id"=>54, "match_id"=>1, "hole_id"=>14, "player_id"=>7, "score"=>5})
