Player.create({"first_name"=>"Sam", "last_name"=>"Askew", "username"=>"asqboi69", "strengths"=>nil, "weaknesses"=>nil, "handicap_text"=>nil, "handicap"=>nil, "team_id"=>nil})
Player.create({"first_name"=>"Ben", "last_name"=>"Oliver", "username"=>"ben", "strengths"=>nil, "weaknesses"=>nil, "handicap_text"=>nil, "handicap"=>nil, "team_id"=>nil})
Player.create({"first_name"=>"Toby", "last_name"=>"Gillanders", "username"=>"tobz", "strengths"=>nil, "weaknesses"=>nil, "handicap_text"=>nil, "handicap"=>nil, "team_id"=>nil})
Player.create({"first_name"=>"Michael", "last_name"=>"Coker", "username"=>"cokes", "strengths"=>nil, "weaknesses"=>nil, "handicap_text"=>nil, "handicap"=>nil, "team_id"=>nil})
Player.create({"first_name"=>"Lee", "last_name"=>"Axten-Rice", "username"=>"lee", "strengths"=>nil, "weaknesses"=>nil, "handicap_text"=>nil, "handicap"=>nil, "team_id"=>nil})
Player.create({"first_name"=>"Calvert", "last_name"=>"Scott", "username"=>"oldskin", "strengths"=>nil, "weaknesses"=>nil, "handicap_text"=>nil, "handicap"=>nil, "team_id"=>1})
Player.create({"first_name"=>"Sam", "last_name"=>"Bourne", "username"=>"bournie", "strengths"=>nil, "weaknesses"=>nil, "handicap_text"=>nil, "handicap"=>nil, "team_id"=>2})
Player.create({"first_name"=>"Hayden", "last_name"=>"Moore", "username"=>"moo", "strengths"=>nil, "weaknesses"=>nil, "handicap_text"=>nil, "handicap"=>nil, "team_id"=>2})
Player.create({"first_name"=>"Jonny", "last_name"=>"Nippert", "username"=>"jfunk", "strengths"=>"", "weaknesses"=>"", "handicap_text"=>"", "handicap"=>nil, "team_id"=>nil})
Player.create({"first_name"=>"Adam", "last_name"=>"Barrett", "username"=>"ayebee", "strengths"=>"", "weaknesses"=>"", "handicap_text"=>"", "handicap"=>nil, "team_id"=>nil})
Player.create({"first_name"=>"Matthew", "last_name"=>"Coker", "username"=>"chubbs", "strengths"=>"STRENGTHS:\r\nC\r\nF cUp\r\nThis man is an absolute fan favorite, often refered to as the\r\nrockstar of the C F cup group. His strengths start straight\r\naway with his shaft handling skills, this leads into a lovely\r\ncontrolled low cut drive. Around the greens his hinge and\r\nhold touch is something to behold. Chubbs is certainly one\r\nto watch out for on this seasons tour\r\nWEAKNESSES:\r\nThe longer the irons get the more his game unravels, catch\r\nChubbs with the right Heckle from 170 or so out and he\r\nstarts wobbling in his boots. Chubbs likes to think of\r\nMATTHEW COKER himself as a bit of a trickster which dosnt always pay off.\r\nhis most famous \"trickshot\" was hitting a tee shot between\r\nNICKNAME: CHUBBS\r\nhis legs and sticking his opponents foot with the ball\r\nHOME CLUB: HASTINGS\r\nBEST C F MOMENT:\r\nCURRENT HANDICAP: 14.8\r\nVomiting in the lovely lush garden surrounding the tee\r\nTROPHIES: CURRENT HOLDER OF box on martinbourgh hole 9! an outstanding effort to\r\n\"THE PIGS\"\r\nkeep the spew down for so long", "weaknesses"=>"", "handicap_text"=>"", "handicap"=>nil, "team_id"=>nil})
Player.create({"first_name"=>"Matt", "last_name"=>"Sroufe ", "username"=>"money", "strengths"=>"", "weaknesses"=>"", "handicap_text"=>"", "handicap"=>nil, "team_id"=>1})
Match.create({"course_id"=>1, "date"=>"2022-04-29"})
Course.create({"name"=>"Terrace Downs"})
Course.create({"name"=>"Pegasus"})
Course.create({"name"=>"Clearwater"})
Hole.create({"course_id"=>1, "par"=>5, "stroke"=>15, "meters"=>nil, "number"=>1})
Hole.create({"course_id"=>1, "par"=>4, "stroke"=>11, "meters"=>nil, "number"=>2})
Hole.create({"course_id"=>1, "par"=>4, "stroke"=>13, "meters"=>nil, "number"=>3})
Hole.create({"course_id"=>1, "par"=>3, "stroke"=>9, "meters"=>nil, "number"=>4})
Hole.create({"course_id"=>1, "par"=>4, "stroke"=>5, "meters"=>nil, "number"=>5})
Hole.create({"course_id"=>1, "par"=>3, "stroke"=>17, "meters"=>nil, "number"=>6})
Hole.create({"course_id"=>1, "par"=>5, "stroke"=>7, "meters"=>nil, "number"=>7})
Hole.create({"course_id"=>1, "par"=>4, "stroke"=>3, "meters"=>nil, "number"=>8})
Hole.create({"course_id"=>1, "par"=>4, "stroke"=>1, "meters"=>nil, "number"=>9})
Hole.create({"course_id"=>1, "par"=>3, "stroke"=>8, "meters"=>nil, "number"=>10})
Hole.create({"course_id"=>1, "par"=>4, "stroke"=>2, "meters"=>nil, "number"=>11})
Hole.create({"course_id"=>1, "par"=>5, "stroke"=>10, "meters"=>nil, "number"=>12})
Hole.create({"course_id"=>1, "par"=>4, "stroke"=>6, "meters"=>nil, "number"=>13})
Hole.create({"course_id"=>1, "par"=>4, "stroke"=>12, "meters"=>nil, "number"=>14})
Hole.create({"course_id"=>1, "par"=>4, "stroke"=>14, "meters"=>nil, "number"=>15})
Hole.create({"course_id"=>1, "par"=>3, "stroke"=>18, "meters"=>nil, "number"=>16})
Hole.create({"course_id"=>1, "par"=>4, "stroke"=>4, "meters"=>nil, "number"=>17})
Hole.create({"course_id"=>1, "par"=>5, "stroke"=>16, "meters"=>nil, "number"=>18})
MatchTeam.create({"match_id"=>1, "team_id"=>1})
MatchTeam.create({"match_id"=>1, "team_id"=>2})
Score.create({"match_id"=>1, "hole_id"=>1, "player_id"=>13, "score"=>4})
Score.create({"match_id"=>1, "hole_id"=>1, "player_id"=>5, "score"=>4})
Score.create({"match_id"=>1, "hole_id"=>1, "player_id"=>3, "score"=>5})
Score.create({"match_id"=>1, "hole_id"=>2, "player_id"=>3, "score"=>4})
Score.create({"match_id"=>1, "hole_id"=>2, "player_id"=>3, "score"=>4})
Score.create({"match_id"=>1, "hole_id"=>2, "player_id"=>13, "score"=>6})
Score.create({"match_id"=>1, "hole_id"=>12, "player_id"=>3, "score"=>8})
Score.create({"match_id"=>1, "hole_id"=>5, "player_id"=>7, "score"=>5})
Score.create({"match_id"=>1, "hole_id"=>2, "player_id"=>5, "score"=>5})
Score.create({"match_id"=>1, "hole_id"=>1, "player_id"=>7, "score"=>5})
Score.create({"match_id"=>1, "hole_id"=>3, "player_id"=>5, "score"=>4})
Score.create({"match_id"=>1, "hole_id"=>3, "player_id"=>3, "score"=>8})
Score.create({"match_id"=>1, "hole_id"=>5, "player_id"=>13, "score"=>4})
Score.create({"match_id"=>1, "hole_id"=>5, "player_id"=>5, "score"=>5})
Score.create({"match_id"=>1, "hole_id"=>5, "player_id"=>3, "score"=>3})
Score.create({"match_id"=>1, "hole_id"=>6, "player_id"=>7, "score"=>4})
Score.create({"match_id"=>1, "hole_id"=>6, "player_id"=>5, "score"=>5})
Score.create({"match_id"=>1, "hole_id"=>6, "player_id"=>3, "score"=>4})
Score.create({"match_id"=>1, "hole_id"=>7, "player_id"=>13, "score"=>5})
Score.create({"match_id"=>1, "hole_id"=>7, "player_id"=>5, "score"=>8})
Score.create({"match_id"=>1, "hole_id"=>7, "player_id"=>3, "score"=>4})
Score.create({"match_id"=>1, "hole_id"=>9, "player_id"=>7, "score"=>2})
Score.create({"match_id"=>1, "hole_id"=>9, "player_id"=>13, "score"=>5})
Score.create({"match_id"=>1, "hole_id"=>9, "player_id"=>5, "score"=>3})
Score.create({"match_id"=>1, "hole_id"=>9, "player_id"=>3, "score"=>7})
Score.create({"match_id"=>1, "hole_id"=>8, "player_id"=>3, "score"=>5})
Score.create({"match_id"=>1, "hole_id"=>8, "player_id"=>13, "score"=>3})
Score.create({"match_id"=>1, "hole_id"=>8, "player_id"=>5, "score"=>3})
Score.create({"match_id"=>1, "hole_id"=>8, "player_id"=>7, "score"=>5})
Score.create({"match_id"=>1, "hole_id"=>10, "player_id"=>7, "score"=>5})
Score.create({"match_id"=>1, "hole_id"=>10, "player_id"=>13, "score"=>2})
Score.create({"match_id"=>1, "hole_id"=>10, "player_id"=>5, "score"=>5})
Score.create({"match_id"=>1, "hole_id"=>10, "player_id"=>3, "score"=>3})
Score.create({"match_id"=>1, "hole_id"=>11, "player_id"=>7, "score"=>3})
Score.create({"match_id"=>1, "hole_id"=>11, "player_id"=>13, "score"=>2})
Score.create({"match_id"=>1, "hole_id"=>11, "player_id"=>5, "score"=>4})
Score.create({"match_id"=>1, "hole_id"=>11, "player_id"=>3, "score"=>3})
Score.create({"match_id"=>1, "hole_id"=>2, "player_id"=>7, "score"=>3})
Score.create({"match_id"=>1, "hole_id"=>12, "player_id"=>5, "score"=>4})
Score.create({"match_id"=>1, "hole_id"=>3, "player_id"=>7, "score"=>5})
Score.create({"match_id"=>1, "hole_id"=>3, "player_id"=>13, "score"=>3})
Score.create({"match_id"=>1, "hole_id"=>13, "player_id"=>5, "score"=>8})
Score.create({"match_id"=>1, "hole_id"=>13, "player_id"=>3, "score"=>4})
Score.create({"match_id"=>1, "hole_id"=>12, "player_id"=>13, "score"=>2})
Score.create({"match_id"=>1, "hole_id"=>13, "player_id"=>13, "score"=>3})
Score.create({"match_id"=>1, "hole_id"=>13, "player_id"=>7, "score"=>3})
Score.create({"match_id"=>1, "hole_id"=>4, "player_id"=>7, "score"=>6})
Score.create({"match_id"=>1, "hole_id"=>4, "player_id"=>5, "score"=>5})
Score.create({"match_id"=>1, "hole_id"=>4, "player_id"=>3, "score"=>3})
Score.create({"match_id"=>1, "hole_id"=>4, "player_id"=>13, "score"=>5})
Score.create({"match_id"=>1, "hole_id"=>7, "player_id"=>7, "score"=>3})
Score.create({"match_id"=>1, "hole_id"=>6, "player_id"=>13, "score"=>6})
Score.create({"match_id"=>1, "hole_id"=>12, "player_id"=>7, "score"=>4})
Score.create({"match_id"=>1, "hole_id"=>14, "player_id"=>13, "score"=>3})
Score.create({"match_id"=>1, "hole_id"=>14, "player_id"=>5, "score"=>7})
Score.create({"match_id"=>1, "hole_id"=>14, "player_id"=>3, "score"=>5})
Score.create({"match_id"=>1, "hole_id"=>14, "player_id"=>7, "score"=>5})
Team.create({"name"=>"Caddyshack"})
